apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "warehouse.fullname" . }}
  labels:
    {{- include "warehouse.labels" . | nindent 4 }}
data:
  app_config.json: |
    {
      "id": "warehouse",
      "display_name": "Telco-Warehouse Portal",
      "port": {{ .Values.containerPort }},
      "dependencies": [
        {
          "id":"{{ .Release.Name }}-promo",
          "urls":["http://{{ .Release.Name }}-promo:8001"]
        },
        {
          "id":"{{ .Release.Name }}-login",
          "urls":["http://{{ .Release.Name }}-login:8081"]
        },
        {
          "id":"{{ .Release.Name }}-inventory",
          "urls":["http://{{ .Release.Name }}-inventory:8003"]
        },
        {
          "id":"{{ .Release.Name }}-plan",
          "urls":["http://{{ .Release.Name }}-plan:8004"]
        },
        {
          "id":"{{ .Release.Name }}-fulfillment",
          "urls":["http://{{ .Release.Name }}-fulfillment:8005"]
        }
      ],
      "database": {
        "name": "",
        "host": "",
        "port": "",
        "user": "",
        "password": ""
      }
    }