apiVersion: v1
kind: Service
metadata:
  name: {{ include "simulator.fullname" . }}
  labels:
    {{- include "simulator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
  selector:
    {{- include "simulator.selectorLabels" . | nindent 4 }}
