apiVersion: v1
kind: Service
metadata:
  name: {{ include "inventory.fullname" . }}
  labels:
    {{- include "inventory.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
  selector:
    {{- include "inventory.selectorLabels" . | nindent 4 }}
