apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fulfillment.fullname" . }}
  labels:
    {{- include "fulfillment.labels" . | nindent 4 }}
data:
  app_config.json: |
    {
      "id": "login",
      "display_name": "Telco-Fulfillment Service",
      "port": {{ .Values.containerPort }},
      "dependencies": [
        {
          "id":"{{ .Release.Name }}-billing",
          "urls":["http://{{ .Release.Name }}-billing:9001"]
        }
      ],
      "database": {
        "name": "",
        "host": "",
        "port": "",
        "user": "",
        "password": ""
      }
    }