apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "billing.fullname" . }}
  labels:
    {{- include "billing.labels" . | nindent 4 }}
data:
  app_config.json: |
    {
      "id": "billing",
      "display_name": "Telco-Billing Service",
      "port": {{ .Values.containerPort }},
      "dependencies": [
      ],
      "database": {
        "name": "",
        "host": "",
        "port": "",
        "user": "",
        "password": ""
      }
    }